#!/bin/sh
# -*- sh -*- vim:set ft=sh ai et sw=4 sts=4:

export LSCOLORS="exfxcxdxbxegedabagacad"
export CLICOLOR=1
export EDITOR="vim"
alias ls="ls -GF"
alias ri="ri -Tf ansi"
export P4CONFIG=".p4config"

PLATFORM=`uname -s`
case "$PLATFORM" in
"Darwin")
  export PATH=$HOME/bin:$PATH
  export MANPATH=/usr/local/share/man:$MANPATH
  if [ -f "/Applications/MacVim.app/Contents/MacOS/Vim" ]
  then
    alias vim="/Applications/MacVim.app/Contents/MacOS/Vim"
    export EDITOR="/Applications/MacVim.app/Contents/MacOS/Vim"
  fi
  alias gvim="mvim"
  alias fpm="/Developer/Applications/Utilities/PackageMaker.app/Contents/Resources/Flat\ Package\ Editor.app/Contents/MacOS/Flat\ Package\ Editor"
  alias mysql.server="sudo /usr/local/mysql/support-files/mysql.server"
  alias xcode="open *.xcodeproj"
  echo -e "\e[00;31mDotfiles Engage!\e[00m"
;;
"Linux")
  echo "Dotfiles Engage!"
  alias mvim="gvim"
  alias ls="ls --color -F"
;;
esac

if [ -f $HOME/.local_profile ]
then
  source $HOME/.local_profile
fi
