if [[ -f /usr/local/opt/chruby/share/chruby/chruby.sh ]]; then
	#echo -e "\e[0;34mchruby engague\e[0m"
	source /usr/local/opt/chruby/share/chruby/chruby.sh
	source /usr/local/opt/chruby/share/chruby/auto.sh
else
	echo -e "\e[0;31m⚠  Ain't got no chruby ⚠\e[0m"
fi
