if [[ -f /usr/local/opt/chruby/share/chruby/chruby.sh ]]; then
	source /usr/local/opt/chruby/share/chruby/chruby.sh
	source /usr/local/opt/chruby/share/chruby/auto.sh
else
	echo "Ain't got no chruby"
	print -n "\a"
fi
